//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoopark
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalsT
    {
        public int IDAnimal { get; set; }
        public string Animal { get; set; }
        public string Name { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public Nullable<int> IDInfo { get; set; }
    
        public virtual Inform Inform { get; set; }
    }
}
